I got this <a href = 'https://machinelearningknowledge.ai/must-see-coronavirus-data-sets-for-data-scientists-and-researchers/'> dataset</a> dataset from Machine Learning Knowledge about corona virus cases that happened around the world in 2020. I was trying to analyze the dataset to try and find the regions and the months that were most affected by the virus.

In [1]:
from csv import reader
import datetime as dt
with open('cases_by_region.csv', encoding = 'utf-8') as df:
    dff = reader(df)
    df3 = list(dff)

In [5]:
df3[:2]

[['SNo',
  'Date',
  'Country',
  'RegionCode',
  'RegionName',
  'Latitude',
  'Longitude',
  'HospitalizedPatients',
  'IntensiveCarePatients',
  'TotalHospitalizedPatients',
  'HomeConfinement',
  'CurrentPositiveCases',
  'NewPositiveCases',
  'Recovered',
  'Deaths',
  'TotalPositiveCases',
  'TestsPerformed'],
 ['0',
  '2020-02-24T18:00:00',
  'ITA',
  '13',
  'Abruzzo',
  '42.35122196',
  '13.39843823',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '']]

In [2]:
newdf = []
for row in df3:
    dates =  row[1]
    RegionName = row[4]
    new_cases = row[12]
    TotalPositiveCases = row[15]
    newdf.append([dates, RegionName, new_cases, TotalPositiveCases])
newdf[:2]

[['Date', 'RegionName', 'NewPositiveCases', 'TotalPositiveCases'],
 ['2020-02-24T18:00:00', 'Abruzzo', '0', '0']]

In [3]:
# Removing headers
headers  = newdf[0]
newdf = newdf[1:] # let our list start from index one onwards (slicing)
newdf[:2]

[['2020-02-24T18:00:00', 'Abruzzo', '0', '0'],
 ['2020-02-24T18:00:00', 'Basilicata', '0', '0']]

In [8]:
# Grouping the regions

Abruzzo = []
Basilicata = []
Calabria= []
Campania= []
Emilia_Romagna = []
Friuli_Venezia_Giulia = []
Latium = []
Liguria = []
Lombardia = []
Marche = []
Molise = []
Piemonte = []
Puglia = []
Sardegna = []
Sicialia = []
Toscana = []
Umbria = []
ValleAosta = []
Veneto = []

totalACases = 0
for row in newdf:
    RegionName = row[1]
    if (RegionName == 'Abruzzo'):
        Abruzzo.append(row)
    elif (RegionName == 'Basilicata'):
        Basilicata.append(row)
    elif (RegionName == 'Calabria'):
        Calabria.append(row)
    elif (RegionName == 'Campania'):
        Campania.append(row)
    elif (RegionName == 'Emilia-Romagna'):
        Emilia_Romagna.append(row)
    elif (RegionName == 'Friuli Venezia Giulia'):
        Friuli_Venezia_Giulia.append(row)
    elif (RegionName == 'Latium'):
        Latium.append(row)
    elif (RegionName == 'Liguria'):
        Liguria.append(row)
    elif (RegionName == 'Lombardia'):
        Lombardia.append(row)
    elif (RegionName == 'Marche'):
        Marche.append(row)
    elif (RegionName == 'Molise'):
        Molise.append(row)
    elif (RegionName == 'Piemonte'):
        Piemonte.append(row)
    elif (RegionName == 'Puglia'):
        Puglia.append(row)
    elif (RegionName == 'Sardegna'):
        Sardegna.append(row)
    elif (RegionName == 'Sicialia'):
        Sicialia.append(row)
    elif (RegionName == 'Toscana'):
        Toscana.append(row)
    elif (RegionName == 'Umbria'):
        Umbria.append(row)
    elif (RegionName == "Valle d'Aosta"):
        ValleAosta.append(row)
    elif (RegionName == 'Veneto'):
        Veneto.append(row)

In [9]:
#total number of cases per region
totalACases = 0
for row in Abruzzo:
    NewCases = int(row[2])
    totalACases += NewCases
totalACases

30324

In [10]:
# A rise in cases can be calculated either by looking at a specific month through all the regions or within a specific region through all the months
# Determining how the cases rose across all the regions throughout the entire year
total2Cases = 0
total3Cases = 0
total4Cases = 0
total5Cases = 0
total6Cases = 0
total7Cases = 0
total8Cases = 0
total9Cases = 0
total10Cases = 0
total11Cases = 0
total12Cases = 0
for row in newdf:
    dates = row[0].replace('T', '')
    newcases = int(row[2])
    specific_month = dt.datetime.strptime(dates, '%Y-%m-%d%H:%M:%S').strftime("%m")

    if (specific_month == '02'):
        total2Cases += newcases
    elif (specific_month == '03'):
        total3Cases += newcases
    elif (specific_month == '04'):
        total4Cases += newcases
    elif (specific_month == '05'):
        total5Cases += newcases
    elif (specific_month == '06'):
        total6Cases += newcases
    elif (specific_month == '07'):
        total7Cases += newcases
    elif (specific_month == '08'):
        total8Cases += newcases
    elif (specific_month == '09'):
        total9Cases += newcases
    elif (specific_month == '10'):
        total10Cases += newcases
    elif (specific_month == '11'):
        total11Cases += newcases
    elif (specific_month == '12'):
        total12Cases += newcases

In [11]:
# Creating a dictionary that contains the months and the total cases in each month
all_months = ['Feb', 'Mar', 'Apr', 'May', 'June', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
monthly_totals = [total2Cases, total3Cases, total4Cases, total5Cases, total6Cases, total7Cases,
               total8Cases, total9Cases, total10Cases, total11Cases, total12Cases]

cases_dict = dict(zip(all_months, monthly_totals))
cases_dict

{'Feb': 1120,
 'Mar': 104664,
 'Apr': 99671,
 'May': 27556,
 'June': 7584,
 'July': 7006,
 'Aug': 21702,
 'Sep': 45623,
 'Oct': 364607,
 'Nov': 922206,
 'Dec': 127322}

In [13]:
# Let now look at how the cases rose through Abruzzo across the year
new_cases_by_month = {}
total_cases_by_month = {}
totalpCases = 0
for row in Abruzzo:
    dates = row[0].replace('T', '')
    newcases = int(row[2])
    daynmonth = dt.datetime.strptime(dates, '%Y-%m-%d%H:%M:%S').strftime("%m-%d")
    
    # increase in cases per daynmonth
    if daynmonth in new_cases_by_month: # increase in cases per daynmonth
        new_cases_by_month[daynmonth] += newcases
    else:
        new_cases_by_month[daynmonth] = newcases
    
    # total number of cases per daynmonth
    NewCases = int(row[2])
    totalpCases += NewCases
    if daynmonth in total_cases_by_month:
        total_cases_by_month[daynmonth] += totalpCases
    else:
        total_cases_by_month[daynmonth] = totalpCases

In [66]:
new_cases_by_month #Specifically for Abruzzo

{'02-24': '0',
 '02-25': '0',
 '02-26': '0',
 '02-27': '1',
 '02-28': '0',
 '02-29': '1',
 '03-01': '3',
 '03-02': '0',
 '03-03': '1',
 '03-04': '1',
 '03-05': '1',
 '03-06': '1',
 '03-07': '2',
 '03-08': '6',
 '03-09': '13',
 '03-10': '8',
 '03-11': '0',
 '03-12': '46',
 '03-13': '5',
 '03-14': '23',
 '03-15': '25',
 '03-16': '39',
 '03-17': '53',
 '03-18': '34',
 '03-19': '122',
 '03-20': '64',
 '03-21': '80',
 '03-22': '58',
 '03-23': '76',
 '03-24': '26',
 '03-25': '124',
 '03-26': '133',
 '03-27': '71',
 '03-28': '116',
 '03-29': '160',
 '03-30': '52',
 '03-31': '56',
 '04-01': '35',
 '04-02': '61',
 '04-03': '66',
 '04-04': '65',
 '04-05': '75',
 '04-06': '18',
 '04-07': '78',
 '04-08': '60',
 '04-09': '72',
 '04-10': '83',
 '04-11': '106',
 '04-12': '40',
 '04-13': '53',
 '04-14': '32',
 '04-15': '29',
 '04-16': '72',
 '04-17': '97',
 '04-18': '44',
 '04-19': '34',
 '04-20': '91',
 '04-21': '55',
 '04-22': '66',
 '04-23': '52',
 '04-24': '18',
 '04-25': '29',
 '04-26': '27',
 '04-27': '15',
 '04-28': '25',
 '04-29': '24',
 '04-30': '7',
 '05-01': '18',
 '05-02': '16',
 '05-03': '32',
 '05-04': '4',
 '05-05': '25',
 '05-06': '22',
 '05-07': '25',
 '05-08': '6',
 '05-09': '8',
 '05-10': '17',
 '05-11': '4',
 '05-12': '8',
 '05-13': '12',
 '05-14': '9',
 '05-15': '12',
 '05-16': '30',
 '05-17': '8',
 '05-18': '7',
 '05-19': '4',
 '05-20': '8',
 '05-21': '7',
 '05-22': '8',
 '05-23': '1',
 '05-24': '5',
 '05-25': '1',
 '05-26': '3',
 '05-27': '5',
 '05-28': '2',
 '05-29': '0',
 '05-30': '0',
 '05-31': '7',
 '06-01': '1',
 '06-02': '4',
 '06-03': '3',
 '06-04': '3',
 '06-05': '2',
 '06-06': '1',
 '06-07': '7',
 '06-08': '0',
 '06-09': '1',
 '06-10': '0',
 '06-11': '1',
 '06-12': '4',
 '06-13': '4',
 '06-14': '4',
 '06-15': '0',
 '06-16': '1',
 '06-17': '2',
 '06-18': '2',
 '06-19': '1',
 '06-20': '1',
 '06-21': '0',
 '06-22': '1',
 '06-23': '0',
 '06-24': '1',
 '06-25': '1',
 '06-26': '1',
 '06-27': '0',
 '06-28': '1',
 '06-29': '1',
 '06-30': '0',
 '07-01': '2',
 '07-02': '3',
 '07-03': '6',
 '07-04': '7',
 '07-05': '4',
 '07-06': '0',
 '07-07': '0',
 '07-08': '1',
 '07-09': '8',
 '07-10': '3',
 '07-11': '2',
 '07-12': '5',
 '07-13': '0',
 '07-14': '0',
 '07-15': '3',
 '07-16': '2',
 '07-17': '1',
 '07-18': '1',
 '07-19': '1',
 '07-20': '6',
 '07-21': '2',
 '07-22': '0',
 '07-23': '10',
 '07-24': '4',
 '07-25': '3',
 '07-26': '1',
 '07-27': '9',
 '07-28': '1',
 '07-29': '4',
 '07-30': '4',
 '07-31': '5',
 '08-01': '5',
 '08-02': '2',
 '08-03': '9',
 '08-04': '3',
 '08-05': '19',
 '08-06': '15',
 '08-07': '39',
 '08-08': '12',
 '08-09': '16',
 '08-10': '7',
 '08-11': '3',
 '08-12': '9',
 '08-13': '16',
 '08-14': '13',
 '08-15': '13',
 '08-16': '2',
 '08-17': '5',
 '08-18': '5',
 '08-19': '7',
 '08-20': '4',
 '08-21': '23',
 '08-22': '24',
 '08-23': '21',
 '08-24': '4',
 '08-25': '10',
 '08-26': '26',
 '08-27': '18',
 '08-28': '20',
 '08-29': '14',
 '08-30': '34',
 '08-31': '4',
 '09-01': '5',
 '09-02': '24',
 '09-03': '24',
 '09-04': '25',
 '09-05': '13',
 '09-06': '26',
 '09-07': '15',
 '09-08': '14',
 '09-09': '5',
 '09-10': '11',
 '09-11': '35',
 '09-12': '11',
 '09-13': '37',
 '09-14': '1',
 '09-15': '18',
 '09-16': '18',
 '09-17': '33',
 '09-18': '54',
 '09-19': '0',
 '09-20': '0',
 '09-21': '72',
 '09-22': '18',
 '09-23': '22',
 '09-24': '17',
 '09-25': '51',
 '09-26': '16',
 '09-27': '47',
 '09-28': '4',
 '09-29': '14',
 '09-30': '23',
 '10-01': '30',
 '10-02': '49',
 '10-03': '42',
 '10-04': '37',
 '10-05': '30',
 '10-06': '48',
 '10-07': '61',
 '10-08': '68',
 '10-09': '103',
 '10-10': '94',
 '10-11': '77',
 '10-12': '117',
 '10-13': '146',
 '10-14': '126',
 '10-15': '203',
 '10-16': '178',
 '10-17': '148',
 '10-18': '221',
 '10-19': '159',
 '10-20': '184',
 '10-21': '252',
 '10-22': '306',
 '10-23': '234',
 '10-24': '375',
 '10-25': '368',
 '10-26': '348',
 '10-27': '345',
 '10-28': '434',
 '10-29': '482',
 '10-30': '428',
 '10-31': '450',
 '11-01': '489',
 '11-02': '478',
 '11-03': '601',
 '11-04': '423',
 '11-05': '571',
 '11-06': '395',
 '11-07': '432',
 '11-08': '584',
 '11-09': '625',
 '11-10': '746',
 '11-11': '662',
 '11-12': '541',
 '11-13': '683',
 '11-14': '939',
 '11-15': '470',
 '11-16': '642',
 '11-17': '729',
 '11-18': '641',
 '11-19': '649',
 '11-20': '705',
 '11-21': '541',
 '11-22': '560',
 '11-23': '640',
 '11-24': '536',
 '11-25': '623',
 '11-26': '570',
 '11-27': '510',
 '11-28': '532',
 '11-29': '413',
 '11-30': '556',
 '12-01': '396',
 '12-02': '381',
 '12-03': '395',
 '12-04': '408',
 '12-05': '376',
 '12-06': '294'}

In [67]:
total_cases_by_month #Specifically for Abruzzo

{'02-24': 0,
 '02-25': 0,
 '02-26': 0,
 '02-27': 1,
 '02-28': 1,
 '02-29': 2,
 '03-01': 5,
 '03-02': 5,
 '03-03': 6,
 '03-04': 7,
 '03-05': 8,
 '03-06': 9,
 '03-07': 11,
 '03-08': 17,
 '03-09': 30,
 '03-10': 38,
 '03-11': 38,
 '03-12': 84,
 '03-13': 89,
 '03-14': 112,
 '03-15': 137,
 '03-16': 176,
 '03-17': 229,
 '03-18': 263,
 '03-19': 385,
 '03-20': 449,
 '03-21': 529,
 '03-22': 587,
 '03-23': 663,
 '03-24': 689,
 '03-25': 813,
 '03-26': 946,
 '03-27': 1017,
 '03-28': 1133,
 '03-29': 1293,
 '03-30': 1345,
 '03-31': 1401,
 '04-01': 1436,
 '04-02': 1497,
 '04-03': 1563,
 '04-04': 1628,
 '04-05': 1703,
 '04-06': 1721,
 '04-07': 1799,
 '04-08': 1859,
 '04-09': 1931,
 '04-10': 2014,
 '04-11': 2120,
 '04-12': 2160,
 '04-13': 2213,
 '04-14': 2245,
 '04-15': 2274,
 '04-16': 2346,
 '04-17': 2443,
 '04-18': 2487,
 '04-19': 2521,
 '04-20': 2612,
 '04-21': 2667,
 '04-22': 2733,
 '04-23': 2785,
 '04-24': 2803,
 '04-25': 2832,
 '04-26': 2859,
 '04-27': 2874,
 '04-28': 2899,
 '04-29': 2923,
 '04-30': 2930,
 '05-01': 2948,
 '05-02': 2964,
 '05-03': 2996,
 '05-04': 3000,
 '05-05': 3025,
 '05-06': 3047,
 '05-07': 3072,
 '05-08': 3078,
 '05-09': 3086,
 '05-10': 3103,
 '05-11': 3107,
 '05-12': 3115,
 '05-13': 3127,
 '05-14': 3136,
 '05-15': 3148,
 '05-16': 3178,
 '05-17': 3186,
 '05-18': 3193,
 '05-19': 3197,
 '05-20': 3205,
 '05-21': 3212,
 '05-22': 3220,
 '05-23': 3221,
 '05-24': 3226,
 '05-25': 3227,
 '05-26': 3230,
 '05-27': 3235,
 '05-28': 3237,
 '05-29': 3237,
 '05-30': 3237,
 '05-31': 3244,
 '06-01': 3245,
 '06-02': 3249,
 '06-03': 3252,
 '06-04': 3255,
 '06-05': 3257,
 '06-06': 3258,
 '06-07': 3265,
 '06-08': 3265,
 '06-09': 3266,
 '06-10': 3266,
 '06-11': 3267,
 '06-12': 3271,
 '06-13': 3275,
 '06-14': 3279,
 '06-15': 3279,
 '06-16': 3280,
 '06-17': 3282,
 '06-18': 3284,
 '06-19': 3285,
 '06-20': 3286,
 '06-21': 3286,
 '06-22': 3287,
 '06-23': 3287,
 '06-24': 3288,
 '06-25': 3289,
 '06-26': 3290,
 '06-27': 3290,
 '06-28': 3291,
 '06-29': 3292,
 '06-30': 3292,
 '07-01': 3294,
 '07-02': 3297,
 '07-03': 3303,
 '07-04': 3310,
 '07-05': 3314,
 '07-06': 3314,
 '07-07': 3314,
 '07-08': 3315,
 '07-09': 3323,
 '07-10': 3326,
 '07-11': 3328,
 '07-12': 3333,
 '07-13': 3333,
 '07-14': 3333,
 '07-15': 3336,
 '07-16': 3338,
 '07-17': 3339,
 '07-18': 3340,
 '07-19': 3341,
 '07-20': 3347,
 '07-21': 3349,
 '07-22': 3349,
 '07-23': 3359,
 '07-24': 3363,
 '07-25': 3366,
 '07-26': 3367,
 '07-27': 3376,
 '07-28': 3377,
 '07-29': 3381,
 '07-30': 3385,
 '07-31': 3390,
 '08-01': 3395,
 '08-02': 3397,
 '08-03': 3406,
 '08-04': 3409,
 '08-05': 3428,
 '08-06': 3443,
 '08-07': 3482,
 '08-08': 3494,
 '08-09': 3510,
 '08-10': 3517,
 '08-11': 3520,
 '08-12': 3529,
 '08-13': 3545,
 '08-14': 3558,
 '08-15': 3571,
 '08-16': 3573,
 '08-17': 3578,
 '08-18': 3583,
 '08-19': 3590,
 '08-20': 3594,
 '08-21': 3617,
 '08-22': 3641,
 '08-23': 3662,
 '08-24': 3666,
 '08-25': 3676,
 '08-26': 3702,
 '08-27': 3720,
 '08-28': 3740,
 '08-29': 3754,
 '08-30': 3788,
 '08-31': 3792,
 '09-01': 3797,
 '09-02': 3821,
 '09-03': 3845,
 '09-04': 3870,
 '09-05': 3883,
 '09-06': 3909,
 '09-07': 3924,
 '09-08': 3938,
 '09-09': 3943,
 '09-10': 3954,
 '09-11': 3989,
 '09-12': 4000,
 '09-13': 4037,
 '09-14': 4038,
 '09-15': 4056,
 '09-16': 4074,
 '09-17': 4107,
 '09-18': 4161,
 '09-19': 4161,
 '09-20': 4161,
 '09-21': 4233,
 '09-22': 4251,
 '09-23': 4273,
 '09-24': 4290,
 '09-25': 4341,
 '09-26': 4357,
 '09-27': 4404,
 '09-28': 4408,
 '09-29': 4422,
 '09-30': 4445,
 '10-01': 4475,
 '10-02': 4524,
 '10-03': 4566,
 '10-04': 4603,
 '10-05': 4633,
 '10-06': 4681,
 '10-07': 4742,
 '10-08': 4810,
 '10-09': 4913,
 '10-10': 5007,
 '10-11': 5084,
 '10-12': 5201,
 '10-13': 5347,
 '10-14': 5473,
 '10-15': 5676,
 '10-16': 5854,
 '10-17': 6002,
 '10-18': 6223,
 '10-19': 6382,
 '10-20': 6566,
 '10-21': 6818,
 '10-22': 7124,
 '10-23': 7358,
 '10-24': 7733,
 '10-25': 8101,
 '10-26': 8449,
 '10-27': 8794,
 '10-28': 9228,
 '10-29': 9710,
 '10-30': 10138,
 '10-31': 10588,
 '11-01': 11077,
 '11-02': 11555,
 '11-03': 12156,
 '11-04': 12579,
 '11-05': 13150,
 '11-06': 13545,
 '11-07': 13977,
 '11-08': 14561,
 '11-09': 15186,
 '11-10': 15932,
 '11-11': 16594,
 '11-12': 17135,
 '11-13': 17818,
 '11-14': 18757,
 '11-15': 19227,
 '11-16': 19869,
 '11-17': 20598,
 '11-18': 21239,
 '11-19': 21888,
 '11-20': 22593,
 '11-21': 23134,
 '11-22': 23694,
 '11-23': 24334,
 '11-24': 24870,
 '11-25': 25493,
 '11-26': 26063,
 '11-27': 26573,
 '11-28': 27105,
 '11-29': 27518,
 '11-30': 28074,
 '12-01': 28470,
 '12-02': 28851,
 '12-03': 29246,
 '12-04': 29654,
 '12-05': 30030,
 '12-06': 30324}

In [19]:
#finding t high risk region by looking at the cases for a random month
totalACases = 0
totalBCases = 0
totalCCases = 0
totalCalCases = 0
totalECases = 0
totalFCases = 0
totalLaCases = 0
totalLiCases = 0
totalLoCases = 0
totalMCases = 0
totalMoCases = 0
totalBoCases = 0
totalTrCases = 0
totalPuCases = 0
totalPiCases = 0
totalSCases = 0
totalSiCases = 0
totalTCases = 0
totalUCases = 0
totalVaCases = 0
totalVCases = 0
for row in newdf:
    dates = row[0].replace('T', '')
    NewCases = int(row[2])
    specific_month = dt.datetime.strptime(dates, '%Y-%m-%d%H:%M:%S').strftime("%m")
    
    if (specific_month == '06'):
        if (row[1] == 'Abruzzo'):
            totalACases += NewCases
        elif (row[1] == 'Basilicata'):
            totalBCases += NewCases
        elif (row[1] == 'Calabria'):
            totalCCases += NewCases
        elif (row[1] == 'Campania'):
            totalCalCases += NewCases
        elif (row[1] == 'Emilia-Romagna'):
            totalECases += NewCases
        elif (row[1] == 'Friuli Venezia Giulia'):
            totalFCases += NewCases
        elif (row[1] == 'Latium'):
            totalLaCases += NewCases
        elif (row[1] == 'Liguria'):
            totalLiCases += NewCases
        elif (row[1] == 'Lombardia'):
            totalLoCases += NewCases
        elif (row[1] == 'Marche'):
            totalMCases += NewCases
        elif (RegionName == 'Molise'):
            totalMoCases += NewCases
        elif (RegionName == 'P.A. Bolzano'):
            totalBoCases += NewCases
        elif (RegionName == 'P.A. Trento'):
            totalTrCases += NewCases
        elif (row[1] == 'Piemonte'):
            totalPiCases += NewCases
        elif (row[1] == 'Puglia'):
            totalPuCases += NewCases
        elif (row[1] == 'Sardegna'):
            totalSCases += NewCases
        elif (row[1] == 'Sicialia'):
            totalSiCases += NewCases
        elif (row[1] == 'Toscana'):
            totalTCases += NewCases
        elif (row[1] == 'Umbria'):
            totalUCases += NewCases
        elif (row[1] == "Valle d'Aosta"):
            totalVaCases += NewCases
        elif (row[1] == 'Veneto'):
            totalVCases += NewCases

In [20]:
all_regions = ['Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Emilia_Romagna', 'Friuli', 'Latium' , 'Liguria', 'Lombardia', 'Marche',
              'Molise', 'Piemonte', 'Puglia', 'P.A. Trento', 'P.A. Bolzano' 'Sardegna', 'Sicialia' ,'Toscana', 'Trentino', 'Umbria', 'ValleAosta', 'Veneto']
monthly_total = [totalACases , totalBCases , totalCCases ,totalCalCases ,totalECases ,totalFCases ,totalLaCases ,totalLiCases ,totalLoCases,
                 totalMCases,totalMoCases,totalPiCases,totalPuCases,totalBoCases, totalTrCases, totalSCases,totalSiCases,totalTCases,totalUCases,totalVaCases,totalVCases ]

cases_dict = dict(zip(all_regions, monthly_total))
cases_dict

{'Abruzzo': 48,
 'Basilicata': 3,
 'Calabria': 24,
 'Campania': -112,
 'Emilia_Romagna': 706,
 'Friuli': 35,
 'Latium': 0,
 'Liguria': 314,
 'Lombardia': 4933,
 'Marche': 52,
 'Molise': 0,
 'Piemonte': 712,
 'Puglia': 37,
 'P.A. Trento': 0,
 'P.A. BolzanoSardegna': 0,
 'Sicialia': 19,
 'Toscana': 0,
 'Trentino': 146,
 'Umbria': 10,
 'ValleAosta': 11,
 'Veneto': 134}